#!/bin/bash
# ===========================================================
#  rentalrdp.com — INSTALL PRODUCTION (Docker, 1 perintah)
#  Cocok untuk: VPS Ubuntu/Debian (DigitalOcean/Vultr/dll)
#  Cara: chmod +x install.sh && ./install.sh
# ===========================================================
set -e

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
ok()   { echo -e "${GREEN}[✓]${NC} $1"; }
info() { echo -e "${CYAN}[i]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }
err()  { echo -e "${RED}[✗]${NC} $1"; exit 1; }

cd "$(dirname "$0")"

echo ""
echo "=============================================="
echo "  rentalrdp.com — INSTALL PRODUCTION (Docker)"
echo "=============================================="
echo ""

# ─── 1. CEK/INSTALL DOCKER ──────────────────────
if ! command -v docker >/dev/null 2>&1; then
  info "Docker belum terinstall. Menginstall Docker..."
  if [ -f /etc/debian_version ]; then
    apt-get update -qq && apt-get install -y -qq docker.io docker-compose-plugin >/dev/null 2>&1
  elif command -v yum >/dev/null 2>&1; then
    yum install -y docker >/dev/null 2>&1
  else
    err "Gagal install Docker otomatis. Install manual: https://docs.docker.com/engine/install/"
  fi
  systemctl enable --now docker >/dev/null 2>&1
  ok "Docker terinstall."
else
  ok "Docker OK: $(docker --version | head -1)"
fi

# Pastikan docker compose (v2) tersedia
if ! docker compose version >/dev/null 2>&1; then
  err "docker compose (v2) tidak ditemukan. Install: https://docs.docker.com/compose/install/linux/"
fi

# ─── 2. BUAT .env (jika belum ada) ───────────────
if [ -f .env ]; then
  warn "File .env sudah ada — tidak ditimpa. Lewati."
else
  info "Membuat .env dengan secrets otomatis..."

  # Generate secrets
  if command -v openssl >/dev/null 2>&1; then
    JWT_SECRET=$(openssl rand -hex 32)
    APP_KEY=$(openssl rand -hex 32)
    POSTGRES_PASS=$(openssl rand -base64 24 | tr -dc 'a-zA-Z0-9' | head -c 24)
  else
    JWT_SECRET=$(head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)
    APP_KEY=$(head -c 64 /dev/urandom | od -An -tx1 | tr -d ' \n' | head -c 64)
    POSTGRES_PASS=$(head -c 32 /dev/urandom | base64 | tr -dc 'a-zA-Z0-9' | head -c 24)
  fi

  # Get server IP
  SERVER_IP=$(curl -s --max-time 5 ifconfig.me 2>/dev/null || echo "YOUR_SERVER_IP")

  cat > .env <<EOF
# === rentalrdp.com — PRODUCTION ===
# Generated by install.sh pada $(date -u +"%Y-%m-%d %H:%M:%S UTC")

PORT=3000
APP_URL=http://${SERVER_IP}:3000
APP_NAME=Rental PC by Miriprian

# Database (Postgres via Docker — JANGAN DIUBAH kecuali pakai DB eksternal)
DATABASE_URL=postgres://rentalrdp:${POSTGRES_PASS}@db:5432/rentalrdp
POSTGRES_PASSWORD=${POSTGRES_PASS}

# Secrets (JANGAN DIUBAH setelah generate!)
JWT_SECRET=${JWT_SECRET}
APP_KEY=${APP_KEY}

# Admin login
SEED_ADMIN_USER=obake
SEED_ADMIN_PASS=obake
SEED_ADMIN_EMAIL=obake@rentalrdp.com

# Katalog
SEED_DEMO_PCS=false

# Keamanan
CORS_ORIGIN=http://${SERVER_IP}:3000
RATE_LIMIT_WINDOW_MS=60000
RATE_LIMIT_MAX=120
LOGIN_RATE_MAX=15
COOKIE_SECURE=false
TRUST_PROXY=true
EOF

  ok "File .env dibuat."
  warn ">>> PERHATIAN: Simpan APP_KEY & JWT_SECRET! <<<"
  info "APP_URL diset ke: http://${SERVER_IP}:3000"
fi

# ─── 3. BANGUN & JALANKAN DOCKER ────────────────
info "Building & menjalankan container..."
docker compose up -d --build

# Tunggu app siap
info "Menunggu aplikasi siap..."
for i in $(seq 1 30); do
  if curl -sf http://localhost:3000/api/health >/dev/null 2>&1; then
    ok "Aplikasi siap!"
    break
  fi
  [ $i -eq 30 ] && err "Aplikasi gagal start. Cek: docker compose logs app"
  sleep 2
done

# ─── 4. MIGRATE + SEED ──────────────────────────
info "Menjalankan migrasi database..."
docker compose exec -T app bun run src/db/migrate.ts 2>/dev/null || true
ok "Migrasi selesai."

info "Menjalankan seed (admin + plans)..."
docker compose exec -T app bun run src/db/seed.ts 2>/dev/null || true
ok "Seed selesai."

# ─── 5. SELESAI ──────────────────────────────────
echo ""
echo "=============================================="
echo -e " ${GREEN}INSTALL SELESAI!${NC}"
echo "=============================================="
echo ""
echo "  Website  : http://${SERVER_IP}:3000"
echo "  Login    : obake / obake"
echo "  DB Pass  : lihat file .env (POSTGRES_PASSWORD)"
echo ""
echo "  PENTING:"
echo "  1. Buka http://${SERVER_IP}:3000 di browser"
echo "  2. Login obake/obake → SEGERA ganti password!"
echo "  3. Install .exe agent di PC RDP yang mau disewakan"
echo ""
echo "  Perintah umum:"
echo "    docker compose logs -f        ← lihat log real-time"
echo "    docker compose restart        ← restart server"
echo "    docker compose down           ← stop server"
echo "    docker compose up -d          ← start server"
echo "    chmod +x manage.sh && ./manage.sh  ← menu manage"
echo ""
echo "=============================================="
